openapi: 3.0.0
info:
  title: Docs API Basic CRUD
  description: API Basic CRUD (Auth, Users)
  version: 1.1.0
servers:
  - url: http://localhost:8080
    description: Optional server description, e.g. Main Local server
components:
  securitySchemes:
    bearerAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /api/auth/login:
    post:
      summary: Returns a jwt token.
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:      # Request body contents
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /api/users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      # security:
      # - bearerAuth: []  # <-- use the same name here
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string